Travis build configuration with heroku deployment
areai51/fusion pull request #33
Opened 2017-09-04 18:07 UTC by vinaymavi

Pull request contains code for issues #13 #29

2017-09-04 18:36 UTC, vinaymavi commented
Travis heroku deployment guide - https://docs.travis-ci.com/user/deployment/heroku/

2017-09-05 18:43 UTC, areai51 commented
Hey  @vinaymavi Travis Config and Heroku deployment is a great PR. thanks a ton for this. @sbmadhav @vichu1988  can either of you do a quick review of this so that I can merge it to master before it gets too late.

2017-09-07 12:58 UTC, sbmadhav requested changes

2017-09-07 12:58 UTC, sbmadhav commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
We should not commit the API Key. Is it possible to move this to runtime config?

2017-09-07 12:58 UTC, sbmadhav commented on package.json
>      "heroku-postbuild": "next build"
Can this use the same convention as others to 
 `"heroku-postbuild": "npm run build"`
That way not many changes if we plan to move out next later on

2017-09-07 16:54 UTC, vichu1988 commented
Add CI pill onto readme
and also update Read me to point to demo site.

2017-09-07 17:32 UTC, vinaymavi commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
@sbmadhav  rung config is a great idea, i need to check how to implement it. 
This api key is not the original one, it is a hash that generated by **travis CLI**.
can we continue current approach? if no, please provide some pointer how we can implement **run config**?

2017-09-07 17:49 UTC, vinaymavi commented on package.json
>      "heroku-postbuild": "next build"
done.

2017-09-07 17:55 UTC, sbmadhav commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
If API key is a hash that generated by Travis CLI, would that mean that someone else with the key can not connect to the same CLI? Is there another password that you use to connect?

2017-09-07 18:02 UTC, vinaymavi commented
@vichu1988 CI pill and demo site link updated, can we add demo link in website section also?
![image](https://user-images.githubusercontent.com/1610828/30177867-b50df82a-9424-11e7-9859-29194b7bc6dd.png)

2017-09-07 18:06 UTC, vinaymavi commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
I am not sure @sbmadhav, just used the document -  https://docs.travis-ci.com/user/deployment/heroku/ and it suggest this method.

2017-09-08 18:16 UTC, sbmadhav approved these changes

2017-09-08 18:34 UTC, sbmadhav commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
Ah! okay. As long as it is the public key we are good. I assume you have run this step correct ?
`travis encrypt $(heroku auth:token) --add deploy.api_key`

2017-09-08 19:12 UTC, sbmadhav commented
@areai51  - we are good to merge this pull request now.

2017-09-08 19:15 UTC, vinaymavi commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
yes, i ran same command.

2017-09-09 07:11 UTC, vish288 reviewed
Please change 
`
"test": "echo \"Error: no test specified\" && exit 1",
`
to 
`
"test": "npm run lint",
`

2017-09-09 07:11 UTC, vish288 commented on .travis.yml
> +    secure: SSnj6mv6oJ/riKhkcGFG3pCqkobkd20VODhYIbAHE6eYDUZg7onOI00s7Aj7TZkvyJEeudVRdplNDFgAy5AFeVq6MbdQgkXgBST4XWXExF5rneZ06YqwKOokCARYfmx2Kw+25yiI87AJkY2CuS909kOFDk7VbbnJIu8McBLDTx+K076QrOkZFZWtSdx
easier way would be enable it via owners and co-owners. @areai51 : Lets take out api key from the config and switch on travis CI build via owner integration of the repo. Could you do that pls?

2017-09-09 07:11 UTC, vish288 commented on package.json
> -    "test": "echo \"Error: no test specified\" && exit 1",
point test to as of now run lint alone. any component we touch , lets ensure we clean up any and all linting errors.

2017-09-09 16:13 UTC, merged