Corrected theme prop value in buttonstyle
areai51/fusion pull request #64
Opened 2017-12-24 22:15 UTC by kumarranjansingh

const buttonStyle = css`
-    background-color:${props => props.theme.buttonColor}; 
-    color:${props => props.theme.buttonTextColor};
In the above lines how the context of props is  retained (in the browser if u check, this two property are taken as invalid)
**My solution**
buttonStyle = theme => css`
+	background-color: ${theme.buttonColor};
+	color: ${theme.buttonTextColor};

and called buttonStyle function from button context passing correct props.

2018-01-01 14:24 UTC, vichu1988 commented
@kumarranjansingh : Lint the file and use 2 spaces instead of tab and update back to the commit.

2018-01-01 14:26 UTC, vish288 requested changes
2 spaces instead of tabs. change that and this can be merged.
Context passing is cleaner 👏

2018-01-02 07:38 UTC, kumarranjansingh commented
I have use prettier plugin while formatting the code. Can we update the editorcofig file, as tabs are used in in the config file?

2018-02-07 23:21 UTC, sbmadhav commented
Please fix the conflicts

2018-06-29 18:20 UTC, closed without merging